version: 0.2

phases:
  install:
    runtime-version:
        nodejs: 20

    commands:
      - echo Entered the install phase...
      
    finally:
      - echo This always runs even if the update or install command fails 

  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - npm install --prefix ./front

    finally:
      - echo This always runs even if the login command fails 

  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - npm run build --prefix ./front

    finally:
      - echo This always runs even if the install command fails
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
  base-directory: ./front/dist # Cambia esto según tu estructura de directorios

cache:
  paths:
    - ./front/node_modules/**/* # Cache para acelerar futuras construcciones