version: 0.2

phases:
  install:
    runtime-version:
        nodejs: 22

    commands:
      - echo Entered the install phase...
      - npm install --prefix ./front
      
    finally:
      - echo This always runs even if the update or install command fails 

  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - npm run build --prefix ./front


    finally:
      - echo This always runs even if the install command fails

# artifacts:
#   files:
#     - ./front/dist